# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('input_description', models.TextField(null=True)),
                ('output_description', models.TextField(null=True)),
                ('sample_input', models.TextField(null=True)),
                ('sample_output', models.TextField(null=True)),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('submission_number', models.IntegerField(default=0)),
                ('accepted_number', models.IntegerField(default=0)),
                ('wrong_answer_number', models.IntegerField(default=0)),
                ('time_limit_number', models.IntegerField(default=0)),
                ('memory_limit_number', models.IntegerField(default=0)),
                ('runtime_error_number', models.IntegerField(default=0)),
                ('output_limit_number', models.IntegerField(default=0)),
                ('compile_error_number', models.IntegerField(default=0)),
                ('presentation_error_number', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'problems',
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'problem_tag',
            },
        ),
        migrations.AddField(
            model_name='problems',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problems.ProblemTag'),
        ),
    ]
